# Generated by Django 5.2.7 on 2026-03-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='course',
            field=models.CharField(default='All Courses', max_length=100),
        ),
    ]
